version: '3.9'

services:
    touitomamout:
    container_name: "touitomamout"
    image: kureu02/touitomamout:latest
    restart: unless-stopped
    environment:
      - ENV_FILE=/data/.env
      - STORAGE_DIR=/data
    volumes:
      - ./data:/data
